/**
 * Created by zhandalin on 2017-04-19 11:26.
 * 说明:定义一些基本东西
 */
#ifndef BZFFMPEG_BZCOMMON_H
#define BZFFMPEG_BZCOMMON_H


#define MEDIA_INFO_WHAT_VIDEO_DURATION 1
#define MEDIA_INFO_WHAT_VIDEO_ROTATE 2
#define MEDIA_INFO_WHAT_VIDEO_WIDTH 3
#define MEDIA_INFO_WHAT_VIDEO_HEIGHT 4


#endif //BZFFMPEG_BZCOMMON_H
